# Generated by Django 5.2.5 on 2025-08-10 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='campus_type',
            field=models.CharField(choices=[('ON', 'On-Campus'), ('OFF', 'Off-Campus')], default='ON', max_length=3),
        ),
        migrations.AddField(
            model_name='post',
            name='company',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='role',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
