# Generated by Django 5.2.5 on 2025-08-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_campus_type_post_company_post_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='salary_range',
            field=models.CharField(default='Not specified', max_length=50),
        ),
    ]
